// Do not edit this file manually
export const enabledBlocks = [
  'openai',
  'zemantic-ai',
  'cal-com',
  'chat-node',
  'qr-code',
  'dify-ai',
  'mistral',
  'elevenlabs',
  'together-ai',
  'web-xr',
  'web-r',
  'webar',
  'wexr',
  'webar',
] as const
